:icons: font
:name: Markup editor

= {name} (Lo-Fi prototyp)
MI-NUR

== O projektu
Stručný popis:: Webový editor značkovacích jazyků pro pokročilé uživatele.
Platforma:: Webový prohlížeč (editor je komponenta použitelná v rámci webové aplikace)

=== Autoři
 *Šmolík Jaroslav* (vedoucí týmu)::
    * mailto:smolijar@fit.cvut.cz[]
    * Organizace týmu, diskuse osnovy zprávy, brainstorming features, tasklist graph, návrh finálních textů, návrh wireframes
 Uhnák Peter::
    * mailto:uhnakpet@fit.cvut.cz[]
    * Diskuse osnovy zprávy, brainstorming features, revize textů, revize tasklist grafu, revize wireframes.
 Špak Maroš::
    * mailto:spakmaro@fit.cvut.cz[]
    * Diskuse osnovy zprávy, brainstorming features, revize textů, revize tasklist grafu, revize wireframes.
 Chmelař Petr::
    * mailto:chmelpe7@fit.cvut.cz[]
    * Diskuse osnovy zprávy, brainstorming features, revize textů, revize tasklist grafu, revize wireframes.

== Product statement

Markup editor je webová embedovatelná komponenta pro editaci dokumentů v jazycích LML (Lightweight Markup Language).
Editor je určen pro technicky zdatné uživatele, u kterých se předpokládá

- znalost syntaxe použitého LML a 
- zkušenost s IDE, či editory zdrojových kódů.

Cílem je zprostředkování efektivního psaní dokumentů těmto uživatelům.

== Business requirements

Cílem editoru je efektivní použití pro danou cílovou skupinu.
Prioritou při editování dokumentu je jeho obsah, nikoli vzhled.
Přesto že se jedná o editor dokumentů, je snahou přiblížit se kodérským editorům, kde má uživatel přímou kontrolu nad zdrojovým kódem dokumentu, než nabízet omezený WYSIWYG editor.
Pohodlnost WYSIWYG editoru je kompenzována real-time náhledem.
Výsledná komponenta je využitelná jako editor v rámci blogovacího nebo wiki systému.

== Restrictions

Editor bude ve výsledné podobě modulární a poskytovat podporu více jazyků formou modulů.
Pro potřeby projektu budeme uvažovat pouze jazyk Markdown.

Vzhledem k rozsahu projektu předpokládáme, že nestihneme implementovat všechny pokročilé funkce editoru, nicméně poskytneme použitelnou implementaci pro editování běžných Markdown dokumentů.

== Feature brainstorming

- Skoč na řádek
- Fullscreen mód
- Vyhledávání v dokumentu
- Autocomplete
- Syntax highlight
- Živý náhled dokumentu
- Dvousloupečkový náhled (zdrojový kód vedle náhledu hotového dokumentu)
- Command pallette
- Document outline preview
- Spellcheck
- Čísla řádek (toggle)
- Zalamování textu
- Sbalování sekcí kódu
- Distraction free mód
- Diff (indikace změněných řádek)
- Běžné klávesové zkratky
- Status bar
- Synchronizované scrollování editoru a preview
- Možnost se proklikávat z preview do editoru
- Přesouvání celých sekcí v dokumentu pomocí outline
- Paste obrázku přímo do editoru, který to promění na správnou LML syntaxi a obrázek uloží
- Manipulace s tabulkami

== Use cases

. **Zvolitelný zobrazovací mód editoru**
+
Uživatel může zvolit zobrazení editoru vhodné pro to, čemu se chce právě věnovat.
+
 - Dvousloupčekový mód editoru (zdrojový kód a náhled) je vhodný pro běžné úpravy, nebo pokud uživatel využívá pokročilé funkce LML a chce zkontrolovat výstup preprocessoru.
 - Náhled pouze zdrojového kódu je vhodný pro nerušené psaní dokumentu, kde se autor soustředí na obsah.
 - Náhled pouze dokumentu je vhodný pro revizi hotového obsahu.

. **Editace dokumentu**
+
Uživatel upravuje dokument přímou editací zdrojového kódu v LML.

. **Navigace v dokumentu**
+
Každý LML vytváří implicitně strukturu dokumentu, pomocí nadpisů různých úrovní.
U větších dokumentů je vhodné využít tuto strukturu pro navigaci ve zdrojovém kódu.

. **Nastaveni voleb editoru**
+
Uživatel musí mít možnost nastavení funkcí editoru, které nesouvisí přímo s editací zdrojového kódu dokumentu.
Například se jedná o přepínání zobrazovacích módu.

. **Pomoc uživateli s pokročilými funkcemi**
+
Editor bude poskytovat uživatelům přirozené UI pro úpravu dokumentu.
Vzhledem k povaze uživatelů se předpokládá, že preferují ovládání pomocí klávesnice před klikáním na popsaná tlačítka.
Bylo by vhodné poskytnout nějakou formu pomoci, tutorialu, či přehledu pokročilých funkcí editoru.

== Tasklist and groups

[NOTE]
====
Protože se jedná o embedovatelnou komponentu, je nutné myslet na to, jak bude vypadat editor na cílové stránce.
Zde předpokládáme dvě možnosti.

Nejedná se o tasky, nicméně tyto možnosti musí být zohledněny při návrhu wireframes.

. Embedování editoru v rámci webové aplikace
+
Editor bude jako element v DOM, mezi ostatními prvky webové stránky.
Je tedy nutné počítat s menším místem pro samotný editor.
. Fullscreen zobrazení editoru
+
Editor bude bez ohledu na umístění v rámci webové stránky umožňovat zobrazení na celou obrazovku, které poskytne uživateli nerušené prostředí, nezávislé na umístění editoru do layoutu.
====

Každý nadpis v této sekci tvoří skupinu tasků.
Skupiny jsou tvořené logickou sounáležitostí tasků.

=== Zobrazovací módy
. Zobrazení zdrojového kódu
. Zobrazení náhledu dokumentu
. Zobrazení zdrojového kódu a náhledu dokumentu ve dvou sloupcích vedle sebe
. Synchronizované scrollování ve dvousloupcovém módu
. Distraction free mód
. Zobrazení/skrytí čísel řádek ve zdrojovém kódu
. Vypnutí/zapnutí zalamování textu
. Vypnutí/zapnutí kontroly pravopisu ve zdrojovém kódu
. Sbalování/rozbalování bloků ve zdrojovém kódu

=== Navigace
. Vyhledávání textu
. Skočit na řádek
. Zobrazení/skrytí struktury dokumentu (outline generovaná z nadpisu)
. Navigace pomocí struktury dokumentu (kliknutí na nadpis vyhledá řádek ve zdrojovém kódu)

=== Editace
. Multicursor editace
. Copy & paste
. Běžné klávesové zkratky
. Autocomplete
. Autosave
. Přesunutí sekcí v outline

=== Nastavení
. Přepínání zobrazovacího módu (zdroj, náhled, vedle sebe)
. Vypnutí/zapnutí zobrazení čísel řádků
. Vypnutí/zapnutí zalamování textu
. Vypnutí/zapnutí kontroly pravopisu
. Vypnutí/zapnutí distraction free módu 
. Vypnutí/zapnutí zobrazení outline
. Nastavení živého náhledu (live, timeout, manual)

=== Přehled možností editoru
. Seznámení se základními klávesovými zkratkami a pokročilou interakcí formou tutoriálu nebo přehledu


== Tasklist graph

:encodedUml: TLIzRjim4Dxv54Iw5V0390YCe4s3BaaB5EYGjWCjNYnL54yWARbDa3Te7o38vB53fix98lkzoXz9f6nt4NJVVVVT3uyyquOfqrI2wBAGDLEieZcJVAKAOq1Ienf8N1LAp7A55Unwh8u1UaSeVSEoSgcmaVmj2bIdfvUiaFCvVNLyV4pkoPVNt-XC5SlSpEQqBM2bYVz6q3882Nf7xmLhPVT4Rt6Xs2ssBBD6rVtbFuyeqo6UZYbS-ZxmcYlyZcttJ4lBzcIDZSeWKgwwTIw0KuvbKu4qZMVL2fpg_vGeexAFQu4Be1eMu0FD2ZCKDcxIuOY6x7HciPYY__DeB2yon-ZmC-Kbs675Flf-dEQrdoAuWRQMYRdedhOliFbT-0wWMjYsxeOMh897EF0uZNSz4WCcxej629qf0Ea9DwDfAGFRAqyyqPXcZPMVCx5TkwF7xOj4ROf-8rmlFXFMfa2fqnKuBxHHB7CulR7YdiSZU64nozv1JkZ7xGFK4cX-OFU-IhTyL38wNOkOTVEhUzA2qUr3j-PG-gH29kl41AjitDf96_ZHhzrAiJgIFZH6539KZE4_EZ_L84IMGnR4zMZkD-F7wUuJjJKaXikMc7sA18cY2JXinVuC1uzlT33wbWOpzZ4WIUNnfAzOMonP5dgNh4rFz7FtlDWygZ3RCWnkYGQdyxbcF4pNtL8ckp_szBlrRL3Km5IMM_8GbpRjVGSQJdACjGUTWtVBFX0rjfl7_f7AGTJ4VKxe9ThIXEDWAP6GuUaRbfw4ApZRVHgRsWqmh3WPLdsFPMqxCEA6TiWtrf5upq1o-_h_0m00

image:http://www.plantuml.com/plantuml/png/{encodedUml}[Takslist graph]

== Wireframe
