:name: Markup editor

= {name} (Lo-Fi prototyp)

== O projektu
Stručný popis:: Webový editor značkovacích jazyků pro pokročilé uživatele.
Platforma:: Webový prohlížeč (editor je komponenta použitelná v rámci webové aplikace)

=== Autoři
 *Šmolík Jaroslav*::
    * mailto:smolijar@fit.cvut.cz[]
    * co dělal...
 Uhnák Peter::
    * mailto:uhnakpet@fit.cvut.cz[]
    * co dělal...
 Špak Maroš::
    * mailto:spakmaro@fit.cvut.cz[]
    * co dělal...
 Chmelař Petr::
    * mailto:chmelpe7@fit.cvut.cz[]
    * co dělal...

== Product statement
== Needs assesment
== Business requirements

Cílem editoru je efektivní použití pro danou cílovou skupinu.
Prioritou při editování dokumentu je jeho obsah, nikoli vzhled.
Přesto že se jedná o editor dokumentů, je snahou přiblížit se kodérským editorům, kde má uživatel přímou kontrolu nad zdrojovým kódem dokumentu, než nabízet omezený WYSIWYG editor.
Pohodlnost WYSIWYG editoru je kompenzována real-time náhledem.
Výsledná komponenta je využitelná jako editor v rámci blogovacího nebo wiki systému.

== Use cases
== Tasklist list
== Tasklist group
== Tasklist graph
== Wireframe
