:name: Markup editor

= {name} (Lo-Fi prototyp)

== O projektu
Stručný popis:: Webový editor značkovacích jazyků pro pokročilé uživatele.
Platforma:: Webový prohlížeč (editor je komponenta použitelná v rámci webové aplikace)

=== Autoři
 *Šmolík Jaroslav*::
    * mailto:smolijar@fit.cvut.cz[]
    * co dělal...
 Uhnák Peter::
    * mailto:uhnakpet@fit.cvut.cz[]
    * co dělal...
 Špak Maroš::
    * mailto:spakmaro@fit.cvut.cz[]
    * co dělal...
 Chmelař Petr::
    * mailto:chmelpe7@fit.cvut.cz[]
    * co dělal...

== Product statement

Markup editor je webová embedovatelná komponenta pro editaci dokumentů v jazycích LML (Lightweight Markup Language).
Editor je určen pro technicky zdatné uživatele, u kterých se předpokládá

- znalost syntaxe použitého LML a 
- zkušenost s IDE, či editory zdrojových kódů.

Cílem je zprostředkování efektivního psaní dokumentů těmto uživatelům.

== Business requirements

Cílem editoru je efektivní použití pro danou cílovou skupinu.
Prioritou při editování dokumentu je jeho obsah, nikoli vzhled.
Přesto že se jedná o editor dokumentů, je snahou přiblížit se kodérským editorům, kde má uživatel přímou kontrolu nad zdrojovým kódem dokumentu, než nabízet omezený WYSIWYG editor.
Pohodlnost WYSIWYG editoru je kompenzována real-time náhledem.
Výsledná komponenta je využitelná jako editor v rámci blogovacího nebo wiki systému.


== Feature brainstorming

- Skoč na řádek
- Fullscreen mód
- Vyhledávání v dokumentu
- Autocomplete
- Syntax highlight
- Živý náhled dokumentu
- Dvousloupečkový náhled (zdrojový kód vedle náhledu hotového dokumentu)
- Command pallette
- Document outline preview
- Spellcheck
- Čísla řádek (toggle)
- Zalamování textu
- Sbalování sekcí kódu
- Distraction free mód
- Diff (indikace změněných řádek)
- Běžné klávesové zkratky
- Status bar
- Synchronizované scrollování editoru a preview
- Možnost se proklikávat z preview do editoru
- Přesouvání celých skecí v dokumentu pomocí outline
- Paste obrázku přímo do editoru, který to promění na správnou LML syntaxi a obrázek uloží
- Manipulace s tabulkami

== Use cases
== Tasklist list
== Tasklist group
== Tasklist graph
== Wireframe
