= Markup editor UI

UI design of web browser embeddable editor for markup editting focused on geeky users.
This project serves as a collaboration platform for user interface design of said editor in course MI-NUR at FIT CTU.

== Milestone phases

=== Lo-fi prototype

link:./1.adoc[Lo-fi prototype]

=== Hi-fi prototype

link:./1.adoc[Rešerše + Hi-fi prototype]

=== Testing

...

== Suggested contribution workflow

When solution of any task agreed upon, create MR with appropriate edits in created templates.

== Using ASCIIDoc

It's easy, readable and rich. Basic syntax is very similliar to Markdown.
See link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[Quick reference guide].

[TIP]
====
To preview documents use http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/#installing-the-development-versions[browser extensions]!

It is, in my expirience, the fastest and easiest way to get started.
====

=== Generate PDF
[TIP]
====
Create PDF using https://github.com/asciidoctor/asciidoctor-pdf[asciidoctor-pdf]

`asciidoctor-pdf -a allow-uri-read X.adoc`

(`-a allow-uri-read` to allow fetching remote assets, e.g. plantuml)
====
