==== Testování #1 - Ing. Jiří Šmolík

===== Informace o testerovi

* 26 let
* Absolvent FIT ČVUT
* Programátor
link:https://www.youtube.com/watch?v=kN7BxRBe-pI[Záznam]

===== Postřehy před testováním

* Tester zná LML jazyky Markdown, Asciidoc.
* Zkušenosti práce s editory VS Code (také Sublime, Atom a další).
* Pro psaní Markdown dokumentů využívá rozšíření v Code.
* Ocenil přehlednost editoru z prvního dojmu

===== Testování dle scénářů
Rychle se zorientoval v editoru, pochopil, k čemu jsou jednotlivé komponenty
(že se jedná o zdrojový kód, náhled, outline apod.), proscroloval editor a outline.
S editací neměl nejmenší problémy.
Nejdříve si nevšiml záznamu o automatickém uložení a řekl, že o obsah při refreshi přijde.
Následně si všiml informace a správně pochopil tuto funkci.

Přesunutí sekcí vykonal velmi rychle.
S outline se již seznámil v předchozím scénáři a již si všiml handles.

K vyhledání textu i sekce použil zkratku `Ctrl+F`,
protože sekci nechtěl hledat ve větším dokumentu očima.
Funkce prokliku z outline si ale byl vědom, vyzkoušel si ji v předchozím scénáři.

Tlačítko command palette po chvíli našel
(neprozradil jsem zkratku a čekal, zda si poradí, pozn.).
Přišlo mu nepřehledné a zavádějící označení některých položek v menu.

===== Shrnutí testování

* Testerovi chyběla funkce goto line (je tam, kvůli absenci helpu není možnost se o ní dozvědět)
* Pro změnu layoutu by očekával tlačítka v rozích sloupečků
* Přál by si volitelnou změnu ("resize") rozdělení editoru a preview
* Ocenil čistý a přehledný design (zůčastnil se testování jako jeden z posledních po velké změně v grafickém vzhledu, pozn.)
